### ISSUE TITLE
LICENSE needed

### ISSUE THREAD

**Issue by napulen** [annakijas1/rebalancing-music-canon#2]
Although the description pledges for open-access, it would be best to have an explicit license in the repo.

Eventually, I'd like to use this data for automatic harmonic analysis (if that aligned with the license of this work).

Thank you for this effort, I think it is great!

**Comment by annakijas1** [comment]
Thanks for your comment, Néstor! I will add a license to the repo.

**Comment by annakijas1** [comment]
Create MIT license for repository
