### ISSUE TITLE
Review spacing

### ISSUE THREAD

**Issue by annakijas1** [annakijas1/rebalancing-music-canon#3]
In the Leon [Momentum file](https://github.com/annakijas1/rebalancing-music-canon/blob/main/_texts/leon-momentum.md) adjust the spacing following the colon in the citation so there is no space between the end of a word and the colon, for example: Momentum: ...

**Comment by phillipw8120** [comment]
Just took care of it! Sorry I keep missing those, I’ll keep an eye out for them now.

From: Anna Kijas ***@***.***>
Date: Thursday, July 22, 2021 at 4:01 PM
To: annakijas1/rebalancing-music-canon ***@***.***>
Cc: Wright, Phillip G ***@***.***>, Assign ***@***.***>
Subject: [annakijas1/rebalancing-music-canon] Review spacing (#3)

In the Leon Momentum file<https://github.com/annakijas1/rebalancing-music-canon/blob/main/_texts/leon-momentum.md> adjust the spacing following the colon in the citation so there is no space between the end of a word and the colon, for example: Momentum: ...

**Comment by phillipw8120** [comment]
Just took care of the other spacing issues and the tempo markings in the Brouwer!
