### ISSUE TITLE
Separate data from presentation

### ISSUE THREAD

**Issue by rettinghaus** [annakijas1/rebalancing-music-canon#4]
It's not a good idea to keep the data with the presentation layer in one repo, not only because most likely different licenses apply. It would be good to separate the MEI files into a separate repo and include this here as a submodule. Then the data can be updated independently from the website.

**Comment by annakijas1** [comment]
Created a repository for the musescore and mei data at https://github.com/annakijas1/rebalancing-music-canon-data
